---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: abangser/java-chrome
    tag: latest

inputs:
- name: spring-microservices

run:
  user: root
  path: spring-cloud-microservice-example/ci/scripts/run_tests.sh
