---
resources:
- name: spring-microservices
  type: git
  source: &repo-source
    uri: https://github.com/abangser/spring-cloud-microservice-example
    branch: master

jobs:
- name: Build
  plan:
  - get: spring-microservices
    trigger: true
  - task: run the test suite
    file: spring-cloud-microservice-example/ci/tasks/run_tests.yml